apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ project_slug }}.fullname" . }}
  labels:
    {{- include "{{ project_slug }}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "{{ project_slug }}.selectorLabels" . | nindent 4 }} 