# Default values for {{cookiecutter.project_slug}}
# This is a YAML-formatted file.

# Global configuration
global:
  environment: production

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: {{cookiecutter.project_slug}}-app
  tag: latest
  pullPolicy: IfNotPresent

# Build arguments for Docker (development only)
buildArgs:
  ENABLE_TESTING: false
  ENABLE_STORYBOOK: false
  ENABLE_LINTING: false
  ENABLE_DEBUG: false

# Service configuration
service:
  type: ClusterIP
  port: {{cookiecutter.app_port}}
  targetPort: {{cookiecutter.app_port}}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: {{cookiecutter.project_slug}}.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m

# Environment variables
env: []

# Development configuration (only mode supported)
dev:
  enabled: true
  service:
    port: {{cookiecutter.app_port}}
    targetPort: {{cookiecutter.app_port}}
  buildArgs:
    ENABLE_TESTING: true
    ENABLE_LINTING: true
    ENABLE_DEBUG: true
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m 